# Generated by Django 4.2.6 on 2023-10-21 08:15

import app_hw_web10.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('path', models.ImageField(upload_to=app_hw_web10.models.update_filename)),
            ],
        ),
    ]
